mod_id=dtbetterend
mod_name=Dynamic Trees for Better End
mod_license=MIT
mod_version=2.2.0
mod_group_id=com.dannykim.dtbetterend
mod_authors=dannykim
mod_description=Compatibility addon between Dynamic Trees and BetterEnd

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.81
loader_version_range=[4,)

dynamic_trees_version=1.8.0-BETA04
dynamic_trees_plus_version=1.0.0
betterend_version=26.1.1

betterend_file_id=8182360
bclib_file_id=8314797
worldweaver_file_id=8314791
wunderlib_file_id=8182329
patchouli_file_id=8404543

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
